export type Param = {key:string; label:string; type?: "number"|"textarea"|"password"|"select"; value?:string|number; options?:string[]; hint?:string};
export type Tool = {id:string; name:string; group:string; summary:string; engine?:boolean; multi?:boolean; extensions?:string[]; output?:string; params?:Param[]; note?:string; noInput?:boolean};
const pages:Param={key:"pages",label:"Pages",hint:"Numbers and ranges, such as 1-3, 5. Leave blank for all where supported."};
const text:Param={key:"text",label:"Text"};
const mode=(label:string,options:string[],value=options[0]):Param=>({key:"mode",label,type:"select",options,value});
const amount=(label:string,value:number):Param=>({key:"amount",label,type:"number",value});
export const tools:Tool[]=[
{id:"edit",name:"Edit PDF",group:"Edit & sign",summary:"Select existing text or images, or add content on the page.",engine:true},
{id:"sign",name:"Sign PDF",group:"Edit & sign",summary:"Draw or import a signature and place it on any page.",engine:true},
{id:"digital_sign",name:"Certificate signing",group:"Edit & sign",summary:"Apply a cryptographic signature with your PFX or P12 certificate.",engine:true,params:[{key:"password",label:"Certificate password",type:"password"},{key:"page",label:"Page (starts at 1)",type:"number",value:1},{...text,label:"Signing reason"}],note:"Certificate trust depends on its issuer. Keep the signed output unchanged to preserve signature validity."},
{id:"fill_forms",name:"Fill PDF forms",group:"Edit & sign",summary:"Fill existing interactive fields and save their values.",engine:true},
{id:"redact",name:"Redact PDF",group:"Edit & sign",summary:"Mark private content and permanently remove it from the saved copy.",engine:true,note:"Redaction rebuilds all pages as images. Searchable text, links, forms, and metadata are removed."},
{id:"compare",name:"Compare PDFs",group:"Edit & sign",summary:"Create a side-by-side report with visible differences highlighted.",engine:true,multi:true},
{id:"flatten",name:"Flatten PDF",group:"Edit & sign",summary:"Bake forms and annotations into image pages.",engine:true,note:"The result preserves appearance but text is no longer selectable."},
{id:"merge",name:"Merge PDF",group:"Organize",summary:"Combine PDFs in the order you choose.",multi:true},
{id:"alternate",name:"Alternate & mix",group:"Organize",summary:"Interleave one page from each document in order.",engine:true,multi:true},
{id:"split",name:"Split every page",group:"Organize",summary:"Save each page as an individual PDF.",output:"folder"},
{id:"split_every",name:"Split in groups",group:"Organize",summary:"Split after a fixed number of pages.",engine:true,output:"folder",params:[amount("Pages per file",2)]},
{id:"split_bookmarks",name:"Split by bookmarks",group:"Organize",summary:"Create files at bookmark page boundaries.",engine:true,output:"folder"},
{id:"split_size",name:"Split by file size",group:"Organize",summary:"Group pages within a target file size.",engine:true,output:"folder",params:[amount("Target megabytes",5)],note:"A single page may exceed the target."},
{id:"split_text",name:"Split by text",group:"Organize",summary:"Start a new file at pages containing your text.",engine:true,output:"folder",params:[text]},
{id:"half",name:"Split pages in half",group:"Organize",summary:"Turn each spread into two pages.",engine:true,params:[mode("Cut direction",["vertical","horizontal"])]},
{id:"extract",name:"Extract pages",group:"Organize",summary:"Keep selected pages in a new PDF.",params:[pages]},
{id:"remove",name:"Remove pages",group:"Organize",summary:"Remove selected pages from a copy.",params:[pages]},
{id:"reorder",name:"Reorder pages",group:"Organize",summary:"Enter every page once in the new sequence.",params:[{key:"order",label:"Page order",hint:"For example: 3, 1, 2"}]},
{id:"rotate",name:"Rotate pages",group:"Organize",summary:"Rotate selected pages or the whole document.",params:[pages,{key:"rotation",label:"Clockwise degrees",type:"select",options:["90","180","270"],value:"90"}]},
{id:"flip",name:"Flip pages",group:"Organize",summary:"Mirror page content horizontally or vertically.",engine:true,params:[mode("Direction",["horizontal","vertical"])]},
{id:"resize",name:"Resize pages",group:"Organize",summary:"Fit content onto a new page size.",engine:true,params:[mode("Paper size",["a4","letter","a3"])]},
{id:"nup",name:"Multiple pages per sheet",group:"Organize",summary:"Arrange several PDF pages on each sheet.",engine:true,params:[{key:"amount",label:"Pages per sheet",type:"select",options:["2","4","6","9"],value:"2"}]},
{id:"bookmarks",name:"Add bookmarks",group:"Organize",summary:"Add named destinations to your PDF.",engine:true,params:[{key:"text",label:"Bookmarks",type:"textarea",hint:"One per line: 2: Chapter two"}]},
{id:"rename_text",name:"Name pages from text",group:"Organize",summary:"Save individual pages named after their first text line.",engine:true,output:"folder"},
{id:"crop",name:"Crop pages",group:"Page details",summary:"Trim the visible area equally on all edges.",params:[{key:"margin",label:"Margin in points (72 = 1 inch)",type:"number",value:18}]},
{id:"page_numbers",name:"Page numbers",group:"Page details",summary:"Add a page number at the bottom of every page."},
{id:"header_footer",name:"Header & footer",group:"Page details",summary:"Add a label with optional page counters.",engine:true,params:[{...text,hint:"Use {page} and {pages} for counters."},mode("Position",["footer","header"])]},
{id:"bates",name:"Bates numbering",group:"Page details",summary:"Add a prefix and sequential six-digit number.",engine:true,params:[{...text,label:"Prefix"},amount("Starting number",1)]},
{id:"watermark",name:"Text watermark",group:"Page details",summary:"Add a centered text watermark.",params:[{...text,hint:"Basic Latin characters, up to 80."}]},
{id:"metadata",name:"Edit metadata",group:"Page details",summary:"Update title, author, subject, and keywords.",params:["title","author","subject","keywords"].map(key=>({key,label:key}))},
{id:"remove_annotations",name:"Remove annotations",group:"Page details",summary:"Remove comments, markup, and interactive form fields."},
{id:"compress",name:"Compress PDF",group:"Optimize & scan",summary:"Reduce image sizes and remove duplicate objects.",engine:true,params:[mode("Compression",["balanced","gentle","small"])],note:"Text stays selectable. Smallest size reduces image quality most."},
{id:"optimize",name:"Lossless optimize",group:"Optimize & scan",summary:"Repack PDF data without reducing image quality.",note:"Some files may not get smaller."},
{id:"grayscale",name:"Grayscale PDF",group:"Optimize & scan",summary:"Create grayscale image pages.",engine:true},
{id:"ocr",name:"OCR searchable PDF",group:"Optimize & scan",summary:"Recognize text in scans and create a searchable PDF.",engine:true,params:[{key:"language",label:"Recognition language",type:"select",options:["eng","hin","eng+hin"],value:"eng"}]},
{id:"deskew",name:"Straighten scans",group:"Optimize & scan",summary:"Detect small page tilts and straighten image pages.",engine:true},
{id:"repair",name:"Repair PDF",group:"Optimize & scan",summary:"Recover readable pages and rebuild the PDF structure.",engine:true,note:"Severely damaged or missing content cannot always be recovered."},
{id:"scan",name:"Scan to PDF",group:"Optimize & scan",summary:"Capture a page through the Windows scanner dialog.",engine:true,noInput:true,note:"Requires a connected scanner with a Windows WIA driver."},
{id:"images_pdf",name:"Images to PDF",group:"Convert",summary:"Combine images into PDF pages in your chosen order.",engine:true,multi:true,extensions:["jpg","jpeg","png","tif","tiff","bmp","webp"]},
{id:"office_pdf",name:"Office to PDF",group:"Convert",summary:"Convert Word, Excel, or PowerPoint with the bundled Office engine.",engine:true,extensions:["doc","docx","xls","xlsx","ppt","pptx","odt","ods","odp"]},
{id:"html_pdf",name:"HTML to PDF",group:"Convert",summary:"Convert a local HTML document to PDF.",engine:true,extensions:["html","htm"],note:"Uses LibreOffice HTML layout; complex web layouts may differ."},
{id:"to_word",name:"PDF to Word",group:"Convert",summary:"Extract editable text and illustrations into a Word document.",engine:true,output:"docx",note:"Layout is reconstructed. Scans remain images unless you run OCR first."},
{id:"to_excel",name:"PDF to Excel",group:"Convert",summary:"Extract tables into worksheets, with text rows as a fallback.",engine:true,output:"xlsx",note:"Review inferred table boundaries and column alignment."},
{id:"to_powerpoint",name:"PDF to PowerPoint",group:"Convert",summary:"Create slides with editable text over the original graphics.",engine:true,output:"pptx",note:"Font appearance may differ. Review the converted slides."},
{id:"to_images",name:"PDF to images",group:"Convert",summary:"Render pages as PNG or JPEG images.",engine:true,output:"folder",params:[pages,mode("Format",["png","jpg"]),amount("Resolution (DPI)",144)]},
{id:"extract_images",name:"Extract images",group:"Convert",summary:"Save embedded images from every page.",engine:true,output:"folder"},
{id:"pdfa",name:"PDF to PDF/A",group:"Convert",summary:"Export an archival PDF/A-2b document through LibreOffice.",engine:true,note:"Review appearance after conversion; specialist archival workflows may require independent validation."},
{id:"text",name:"PDF to text",group:"Convert",summary:"Extract selectable text into a text file.",output:"txt"},
{id:"protect",name:"Protect PDF",group:"Security",summary:"Require a password to open the PDF.",params:[{key:"password",label:"New PDF password",type:"password"}]},
{id:"unlock",name:"Unlock PDF",group:"Security",summary:"Remove a PDF password you know.",params:[{key:"password",label:"Current PDF password",type:"password"}]},
];
